"""Improvement proposal contract for behavioral changes."""

from __future__ import annotations

from datetime import datetime
from typing import Any, Literal

import pydantic as pd

from ash_hawk.strategies import Strategy, SubStrategy


class ImprovementProposal(pd.BaseModel):
    """Structured proposal for improving agent behavior.

    Generated by Ash Hawk's pipeline roles (Analyst, Coach, Architect)
    and subject to curation before becoming persistent lessons.

    Attributes:
        proposal_id: Unique identifier for this proposal.
        origin_run_id: ID of the run that triggered this proposal.
        origin_review_id: ID of the review that generated this proposal.
        target_agent: Agent this proposal applies to.
        proposal_type: Type of improvement (policy, skill, tool, harness, eval).
        title: Short title describing the proposed change.
        rationale: Why this change is needed.
        evidence_refs: References to evidence supporting this proposal.
        expected_benefit: Description of expected improvement.
        risk_level: Risk level of implementing this change.
        diff_payload: Structured change payload (format depends on type).
        rollback_plan: How to revert if the change causes problems.
        status: Current status (pending, approved, rejected, implemented, rolled_back).
        created_at: When the proposal was created.
        reviewed_at: When the proposal was reviewed (if applicable).
        reviewer: Who reviewed the proposal (if applicable).
    """

    proposal_id: str = pd.Field(
        description="Unique identifier for this proposal",
    )
    origin_run_id: str = pd.Field(
        description="ID of the run that triggered this proposal",
    )
    origin_review_id: str | None = pd.Field(
        default=None,
        description="ID of the review that generated this proposal",
    )
    target_agent: str = pd.Field(
        description="Agent this proposal applies to",
    )
    proposal_type: Literal["policy", "skill", "tool", "harness", "eval"] = pd.Field(
        description="Type of improvement",
    )
    title: str = pd.Field(
        description="Short title describing the proposed change",
    )
    rationale: str = pd.Field(
        description="Why this change is needed",
    )
    evidence_refs: list[str] = pd.Field(
        default_factory=list,
        description="References to evidence supporting this proposal",
    )
    expected_benefit: str = pd.Field(
        description="Description of expected improvement",
    )
    risk_level: Literal["low", "medium", "high"] = pd.Field(
        description="Risk level of implementing this change",
    )
    diff_payload: dict[str, Any] = pd.Field(
        default_factory=dict,
        description="Structured change payload (format depends on type)",
    )
    rollback_plan: str | None = pd.Field(
        default=None,
        description="How to revert if the change causes problems",
    )
    status: Literal["pending", "approved", "rejected", "implemented", "rolled_back"] = pd.Field(
        default="pending",
        description="Current status",
    )
    created_at: datetime = pd.Field(
        description="When the proposal was created",
    )
    reviewed_at: datetime | None = pd.Field(
        default=None,
        description="When the proposal was reviewed",
    )
    reviewer: str | None = pd.Field(
        default=None,
        description="Who reviewed the proposal",
    )
    rejection_reason: str | None = pd.Field(
        default=None,
        description="Reason for rejection if status is rejected",
    )
    experiment_id: str | None = pd.Field(
        default=None,
        description="ID of the experiment this proposal belongs to",
    )
    strategy: Strategy | None = pd.Field(
        default=None,
        description="Top-level improvement strategy",
    )
    sub_strategies: list[SubStrategy] = pd.Field(
        default_factory=list,
        description="Sub-strategies this proposal addresses",
    )
    confidence: float | None = pd.Field(
        default=None,
        ge=0.0,
        le=1.0,
        description="Confidence score for this proposal (0.0 to 1.0)",
    )

    model_config = pd.ConfigDict(extra="forbid")
